### ISSUE TITLE
Woocommerce log error when using PHP 8.0

### ISSUE THREAD

**Issue by diegonaranjo** [Ingenico-NPS-Latam/nps-plugin-woocommerce#1]
HI!!! We are using this plugin over 3 years, and allways works fine, but now we are migrating our site to php 8.0 and this error log is present now in backend:

[21-Aug-2021 02:16:53 UTC] PHP Warning:  The magic method WC_Nps::__wakeup() must have public visibility in /public_html/wp-content/plugins/nps-plugin-woocommerce-master/woocommerce-gateway-nps.php on line 102
[21-Aug-2021 02:16:53 UTC] PHP Deprecated:  Required parameter $sanitizeStruc follows optional parameter $k in /public_html/wp-content/plugins/nps-plugin-woocommerce-master/includes/nps-sdk-php-master/src/NpsSDK/Utils.php on line 77

Could you help us solve it?

Another question, do you plan to support the Loco translate plugin?

Best regards.
Diego

**Comment by IngenicoNPSLatam** [comment]
Hi Diego! Sorry for the late response, as soons as we saw the issue we started to work on it. 

We have updated the plugin, in order to solve the warnings that it was generating and now seems to work fine. Feel free to update it and test if the warnings are still showing up. If there is anything else that we have to consider about the plugin, please let us know.

Regarding the Loco translate plugin, we are not planning yet to add the support for it.

Best Regards!

**Comment by diegonaranjo** [comment]
Hi! Well I thank you for the help.
We see that several errors stop appearing, now these 2 are listed.

[07-Sep-2021 13:37:24 UTC] PHP Warning:  Undefined variable $response in /home/u377080590/domains/www/public_html/wp-content/plugins/nps-plugin-woocommerce-master/includes/class-wc-nps-customer.php on line 274
[07-Sep-2021 13:37:24 UTC] PHP Warning:  Attempt to read property "psp_CustomerId" on null in /home/u377080590/domains/www/public_html/wp-content/plugins/nps-plugin-woocommerce-master/includes/class-wc-nps-customer.php on line 274

**Comment by IngenicoNPSLatam** [comment]
Hi Diego, thank you for your feedback! 

As soon as we have the listed warning's fixes uploded into the repository, we will let you know.

Best regards!

**Comment by diegonaranjo** [comment]
Hi! Ok no problem.
By the way, another conflict that we find is that in the detail of the order it does not add the fees to the total of the order. As you can see in the image:
[https://imgur.com/iWVIX00](url)

Best regards.
Diego

**Comment by IngenicoNPSLatam** [comment]
Hi Diego!
We already commited the changes that fix the warnings in **class-wc-nps-customer.php**. Feel free to update the repository and test it out. 

Regarding to the fees, we tried to reproduce the issue but there was no success doing it. We used PHP 8.0.12 and the fees are actually reprecented in the total amount. Can you please provide to us what PHP's version you used to get this issue?

![image](https://user-images.githubusercontent.com/24914148/140188680-5e0cc4d1-1c2b-4e4d-aab6-ce26ca813046.png)

![image](https://user-images.githubusercontent.com/24914148/140188763-ae79d6f8-64a2-496b-9de5-bbe738a6fa8c.png)

Best Regards!

**Comment by diegonaranjo** [comment]
Hi there!
I´m testing the new version, but we have the same behavior, the payment is process but does not add the fee on totals. 
And one thing i note today, when I make the payment, it does not continue to the page of the order placed, it stays on the checkout page.
I see this error when order is placed:

[04-Nov-2021 18:16:18 UTC] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string + string in /home/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php:2080
Stack trace:
#0 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(2095): WC_Abstract_Order->add_order_item_totals_fee_rows()
#1 /home/public_html/wp-content/plugins/woocommerce/templates/emails/email-order-details.php(63): WC_Order->get_order_item_totals()
#2 /home/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/home/u37708059...')
#3 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-emails.php(421): wc_get_template()
#4 /home/public_html/wp-includes/class-wp-hook.php(303): WC_Emails->order_details()
#5 /home/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#6 /home/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#7 /home/public_html/wp-content/plugins/woocommerce/templates/emails/customer-processing-order.php(40): do_action()
#8 /home/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/home/u37708059...')
#9 /home/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(364): wc_get_template()
#10 /home/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email-customer-processing-order.php(113): wc_get_template_html()
#11 /home/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(541): WC_Email_Customer_Processing_Order->get_content_html()
#12 /home/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email-customer-processing-order.php(93): WC_Email->get_content()
#13 /home/public_html/wp-includes/class-wp-hook.php(303): WC_Email_Customer_Processing_Order->trigger()
#14 /home/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#15 /home/public_html/wp-includes/plugin.php(518): WP_Hook->do_action()
#16 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-emails.php(170): do_action_ref_array()
#17 /home/public_html/wp-includes/class-wp-hook.php(303): WC_Emails::send_transactional_email()
#18 /home/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#19 /home/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#20 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(373): do_action()
#21 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(222): WC_Order->status_transition()
#22 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(120): WC_Order->save()
#23 /home/public_html/wp-content/plugins/nps-plugin-woocommerce-master/includes/class-wc-gateway-nps.php(1718): WC_Order->payment_complete()
#24 /home/public_html/wp-content/plugins/nps-plugin-woocommerce-master/includes/class-wc-gateway-nps.php(1196): WC_Gateway_Nps->process_response()
#25 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(980): WC_Gateway_Nps->process_payment()
#26 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1195): WC_Checkout->process_order_payment()
#27 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(466): WC_Checkout->process_checkout()
#28 /home/public_html/wp-includes/class-wp-hook.php(303): WC_AJAX::checkout()
#29 /home/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#30 /home/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#31 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action()
#32 /home/public_html/wp-includes/class-wp-hook.php(303): WC_AJAX::do_wc_ajax()
#33 /home/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#34 /home/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#35 /home/public_html/wp-includes/template-loader.php(13): do_action()
#36 /home/public_html/wp-blog-header.php(19): require_once('/home/u37708059...')
#37 /home/public_html/index.php(17): require('/home/u37708059...')
#38 {main}
  thrown in /home/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 2080


Our HP version is 8.0.7, and woocommerce 5.8

If you want to make test on our site, we can follow by email.

Thanks, Diego.

**Comment by IngenicoNPSLatam** [comment]
Hi Diego!

Thank you for all the information given, it will be very helpful to us in order to reproduce the issue. Let us validate this with that PHP version and we will give you an update. 

In case there is any complication, we can follow this by email. 

Best Regards!

**Comment by diegonaranjo** [comment]
Hi, i solved, in woocommerce taxes options, by checking "Enable rate taxes and calculations".
And have to change the file wc-abstract-order.php with this code on line 2197 (it is needed to add floatval).

'value' => wc_price( 'excl' === $tax_display ? **floatval(**$fee->get_total()**)** : **floatval(**$fee->get_total()**)**+ **floatval(**$fee->get_total_tax()**)**, array( 'currency' => $this->get_currency() ) ),

Best regards.
